
server:  
  port: 8088
  session-timeout: 30  
  tomcat.max-threads: 0  
  tomcat.uri-encoding: UTF-8
  servlet:
    context-path: /NewMapper180831

devtools:
  livereload:
    enabled: true #是否支持livereload
    port: 35729
  restart:
    enabled: true #是否支持热部署



#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params=count: countSql

#characterEncoding=UTF-8
spring: 
  datasource:  
    url : jdbc:mysql://localhost:3306/newmapper?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username : root  
    password : root  
    driverClassName : com.mysql.jdbc.Driver     
  aop: 
    proxy-target-class : true
  jpa:  
    database : MYSQL  
    show-sql : true  
    hibernate:  
      ddl-auto : update  
      #naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy  
    properties:  
      hibernate:  
        dialect : org.hibernate.dialect.MySQL5InnoDBDialect  
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
          
mybatis:
  type-aliases-package: com.jyx.edu.NewMapper180831.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
     cache-enabled : true
     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
     map-underscore-to-camel-case: true


mapper:
  mappers: com.jyx.edu.NewMapper180831.basemapper.BaseMapper
  identity: MYSQL

loging:
  level:
    com.jqmkj.proxy8700.dbinterface : DEBUG